FROM alpine

RUN <<EOF
apk add git
apk add curl
apk add gcc
apk add pkg-config
apk add lua
apk add lua5.4-dev
apk add musl-dev
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
git clone https://github.com/dandyvica/dqy
echo "cd dqy" >compile.sh
echo "git pull" >> compile.sh
echo "source ~/.cargo/env" >> compile.sh
echo "cargo build --release" >> compile.sh
echo "strip /dqy/target/release/dqy" >> compile.sh
echo "#/dqy/scripts/rename_bin.sh"  >> compile.sh
chmod +x compile.sh
EOF

CMD /compile.sh